// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
    // Pre-created shadow DB (owned by the same app role) — avoids granting
    // CREATEDB to the app role just so `prisma migrate dev` can spawn its
    // scratch DB. See https://pris.ly/d/migrate-shadow.
    shadowDatabaseUrl: env('SHADOW_DATABASE_URL'),
  },
});
