/**
 * AWS Secrets Manager wrapper for the world lifecycle. Read paths tolerate
 * `ResourceNotFoundException` so the UI renders even before the reference
 * defaults secret exists.
 */
import {
  CreateSecretCommand,
  DeleteSecretCommand,
  GetSecretValueCommand,
  ResourceNotFoundException,
  SecretsManagerClient,
} from '@aws-sdk/client-secrets-manager';
import { randomBytes } from 'node:crypto';

import {
  OPTIONAL_AI_KEYS,
  REQUIRED_SECRET_KEYS,
  TEMPLATE_DEFAULTS_SECRET_ID,
  type SecretKey,
} from './world-templates-constants';

let clientInstance: SecretsManagerClient | null = null;

function getClient(): SecretsManagerClient {
  if (clientInstance) return clientInstance;
  clientInstance = new SecretsManagerClient({
    region: process.env.AWS_REGION ?? 'eu-west-1',
  });
  return clientInstance;
}

export type SecretValues = Partial<Record<SecretKey, string>>;

export interface TemplateDefaults {
  exists: boolean;
  values: SecretValues;
}

/**
 * Read the reference defaults secret. Returns `exists: false` if absent so
 * the caller can render an empty form instead of erroring.
 */
export async function getTemplateDefaults(): Promise<TemplateDefaults> {
  try {
    const out = await getClient().send(
      new GetSecretValueCommand({ SecretId: TEMPLATE_DEFAULTS_SECRET_ID }),
    );
    const raw = out.SecretString;
    if (!raw) return { exists: true, values: {} };
    const parsed = parseSecretString(raw);
    return { exists: true, values: parsed };
  } catch (err) {
    if (err instanceof ResourceNotFoundException) {
      return { exists: false, values: {} };
    }
    throw err;
  }
}

/**
 * Compose the per-world secret payload: defaults + overrides + autogenerated
 * `ADMIN_CODE` / `JWT_SECRET`. Required keys are always present (empty string
 * if no value); optional AI keys only when `includeAi`.
 */
export function composeSecretPayload(
  defaults: SecretValues,
  overrides: SecretValues,
  options: { includeAi?: boolean } = {},
): Record<string, string> {
  const includeAi = options.includeAi ?? false;
  const merged: Record<string, string> = {};
  const targetKeys: readonly SecretKey[] = includeAi
    ? [...REQUIRED_SECRET_KEYS, ...OPTIONAL_AI_KEYS]
    : REQUIRED_SECRET_KEYS;

  for (const key of targetKeys) {
    merged[key] = overrides[key] ?? defaults[key] ?? '';
  }

  if (!merged.ADMIN_CODE) merged.ADMIN_CODE = generateAdminCode();
  if (!merged.JWT_SECRET) merged.JWT_SECRET = generateJwtSecret();

  return merged;
}

export interface CreateWorldSecretInput {
  secretId: string;
  payload: Record<string, string>;
  description?: string;
}

export interface CreateWorldSecretResult {
  arn: string;
  name: string;
  versionId: string;
}

/** Create the per-world secret. Caller derives the secretId. */
export async function createWorldSecret(
  input: CreateWorldSecretInput,
): Promise<CreateWorldSecretResult> {
  const out = await getClient().send(
    new CreateSecretCommand({
      Name: input.secretId,
      Description: input.description ?? `World secret (${input.secretId})`,
      SecretString: JSON.stringify(input.payload),
    }),
  );
  if (!out.ARN || !out.Name || !out.VersionId) {
    throw new Error('AWS create-secret returned an incomplete response');
  }
  return { arn: out.ARN, name: out.Name, versionId: out.VersionId };
}

export interface DeleteWorldSecretInput {
  secretId: string;
  recoveryDays?: number;
}

export async function deleteWorldSecret(input: DeleteWorldSecretInput): Promise<void> {
  await getClient().send(
    new DeleteSecretCommand({
      SecretId: input.secretId,
      RecoveryWindowInDays: input.recoveryDays ?? 7,
    }),
  );
}

// =============================================================
// Internals
// =============================================================

function parseSecretString(raw: string): SecretValues {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return {};
  }
  if (!parsed || typeof parsed !== 'object') return {};
  const out: SecretValues = {};
  for (const key of [...REQUIRED_SECRET_KEYS, ...OPTIONAL_AI_KEYS]) {
    const v = (parsed as Record<string, unknown>)[key];
    if (typeof v === 'string') out[key] = v;
  }
  return out;
}

const ADMIN_CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

function generateAdminCode(length = 8): string {
  const bytes = randomBytes(length);
  let out = '';
  for (let i = 0; i < length; i++) {
    out += ADMIN_CHARS[bytes[i] % ADMIN_CHARS.length];
  }
  return out;
}

function generateJwtSecret(): string {
  return randomBytes(32).toString('hex');
}
