/**
 * Render the human/IA-facing files that ship inside a world backup zip so the
 * recipient can run the world offline: `.env`, `docker-compose.yml`,
 * `world.json`, and a top-level `README.md`. The four deploy tutorials
 * (local/AWS/Azure/GCP) are rendered separately (Phase 2).
 *
 * Every function here is pure: it takes resolved config and returns a string.
 * The orchestrating CLI is responsible for the non-deterministic bits
 * (generating JWT/admin secrets, stamping the export timestamp).
 */

/** Where to obtain the GPL engine when the prebuilt image isn't reachable. */
export const ENGINE_REPO_URL = 'https://github.com/numengames/numinia-hyperfy2';
export const ENGINE_COMMIT =
  process.env.BACKUP_ENGINE_COMMIT ?? '0e2045370989d051e73f81c7c9d53121d5c374b3';

export interface WorldBackupMeta {
  org: string;
  world: string;
  env: 'pre' | 'pro';
  /** The hostname the world ran on in production (reference only). */
  originalHostname: string;
  /** Source Postgres schema the state came from (reference only). */
  dbSchema: string;
  /** Prebuilt engine image (e.g. `ghcr.io/numengames/numinia-hyperfy2:dev`). */
  engineImage: string;
  /** ISO timestamp of when the backup was produced (stamped by the CLI). */
  exportedAt: string;
  /** Asset counts from the download step. */
  assets: { files: number; bytes: number };
  /** Per-table row counts from the DB export step. */
  db: { tables: Record<string, number> };
  /**
   * Prebuilt engine image tarball bundled into the zip for fully-offline runs
   * (`docker load`). Absent when the image wasn't staged — the recipient then
   * pulls the image or builds it from source (both already documented).
   */
  engineImageTar?: { path: string; bytes: number };
}

export interface LocalRunConfig {
  /** Name of the world folder the engine reads (the `WORLD` env var). */
  worldDir: string;
  port: number;
  /** Freshly generated — NOT the production secret. */
  jwtSecret: string;
  /** Freshly generated — NOT the production admin code. */
  adminCode: string;
  saveInterval: number;
  /** Max upload size in MB. */
  maxUploadSize: number;
}

/**
 * Render the `.env` for a fully-offline local run: SQLite + filesystem assets,
 * no external services. LiveKit/AI are intentionally omitted (the engine
 * degrades gracefully without them).
 */
export function renderEnvFile(cfg: LocalRunConfig): string {
  return [
    '# Local run config generated by Khepri-Forge world backup.',
    '# Fully offline: SQLite + on-disk assets, no AWS/Postgres/LiveKit needed.',
    '# JWT_SECRET and ADMIN_CODE below are FRESH values, not the production ones.',
    '',
    `WORLD=${cfg.worldDir}`,
    `PORT=${cfg.port}`,
    `JWT_SECRET=${cfg.jwtSecret}`,
    `ADMIN_CODE=${cfg.adminCode}`,
    `SAVE_INTERVAL=${cfg.saveInterval}`,
    `PUBLIC_MAX_UPLOAD_SIZE=${cfg.maxUploadSize}`,
    `PUBLIC_WS_URL=ws://localhost:${cfg.port}/ws`,
    `PUBLIC_API_URL=http://localhost:${cfg.port}/api`,
    'ASSETS=local',
    `ASSETS_BASE_URL=http://localhost:${cfg.port}/assets`,
    'COLLECTIONS=local',
    'DB_URI=local',
    '',
  ].join('\n');
}

/**
 * Render `docker-compose.yml` with a single engine service. Defaults to the
 * prebuilt image; a commented `build:` block lets a recipient without registry
 * access build the GPL engine straight from the pinned public commit.
 */
export function renderDockerCompose(meta: WorldBackupMeta, cfg: LocalRunConfig): string {
  const offlineImageHint = meta.engineImageTar
    ? [
        '    # Fully offline? This archive bundles the engine image. Load it once before `up`:',
        `    #   gunzip -c ${meta.engineImageTar.path} | docker load`,
      ]
    : [];
  return [
    '# Run this world locally: `docker compose up`, then open http://localhost:' + cfg.port,
    'services:',
    '  hyperfy:',
    `    image: ${meta.engineImage}`,
    ...offlineImageHint,
    '    # No access to the image registry? Build the GPL engine from source instead:',
    '    # build:',
    `    #   context: ${ENGINE_REPO_URL}.git#${ENGINE_COMMIT}`,
    '    env_file: .env',
    '    ports:',
    `      - "${cfg.port}:${cfg.port}"`,
    '    volumes:',
    `      - ./${cfg.worldDir}:/app/${cfg.worldDir}`,
    '    restart: unless-stopped',
    '',
  ].join('\n');
}

/** Render machine-readable backup metadata. */
export function renderWorldJson(meta: WorldBackupMeta): string {
  return (
    JSON.stringify(
      {
        org: meta.org,
        world: meta.world,
        environment: meta.env,
        originalHostname: meta.originalHostname,
        sourceDbSchema: meta.dbSchema,
        engine: {
          image: meta.engineImage,
          repo: ENGINE_REPO_URL,
          commit: ENGINE_COMMIT,
          bundledTar: meta.engineImageTar?.path ?? null,
          bundledTarBytes: meta.engineImageTar?.bytes ?? null,
        },
        exportedAt: meta.exportedAt,
        contents: {
          assetFiles: meta.assets.files,
          assetBytes: meta.assets.bytes,
          dbRowsByTable: meta.db.tables,
        },
        backupFormat: 1,
      },
      null,
      2,
    ) + '\n'
  );
}

/** Render the top-level README quick-start (detailed tutorials live in docs/). */
export function renderReadme(meta: WorldBackupMeta, cfg: LocalRunConfig): string {
  const tar = meta.engineImageTar;
  const offlineLoadStep = tar
    ? `
This archive bundles the engine image, so it runs with **no internet at all**.
Load it once before the first run:

\`\`\`bash
gunzip -c ${tar.path} | docker load
\`\`\`
`
    : '';
  const engineRow = tar
    ? `\n| \`${tar.path}\` | Prebuilt engine image (${formatBytes(tar.bytes)}) — \`docker load\` for fully-offline runs |`
    : '';
  return `# ${meta.world} — world backup

This archive is a self-contained snapshot of the **${meta.world}** world
(organization \`${meta.org}\`, \`${meta.env}\` environment), exported on
${meta.exportedAt}. It runs offline with Docker — no cloud account required.
${offlineLoadStep}
## Run it locally (1 command)

\`\`\`bash
docker compose up
\`\`\`

Then open <http://localhost:${cfg.port}>. The first boot loads the world state
from \`world/db.sqlite\` and serves assets from \`world/assets/\`.

- **Admin code:** \`${cfg.adminCode}\` (type it in-world to get builder rights)
- Voice/video (LiveKit) is disabled in this offline build; everything else works.

## What's inside

| Path | What it is |
|------|-----------|
| \`world/db.sqlite\` | World state (${sumRows(meta.db.tables)} rows) — entities, blueprints, settings |
| \`world/assets/\` | ${meta.assets.files} asset files (${formatBytes(meta.assets.bytes)}) |
| \`docker-compose.yml\` | One-command local run |
| \`.env\` | Local run config (fresh JWT/admin secrets, not production) |
| \`world.json\` | Machine-readable backup metadata |${engineRow}
| \`docs/\` | Step-by-step deploy guides: local, AWS, Azure, GCP |

## Deploy to the cloud

See \`docs/DEPLOY-LOCAL.md\`, \`docs/DEPLOY-AWS.md\`, \`docs/DEPLOY-AZURE.md\`,
and \`docs/DEPLOY-GCP.md\`. The engine is GPL-3.0 and its source lives at
${ENGINE_REPO_URL} (pinned to commit \`${ENGINE_COMMIT}\`), so you can also build
the image yourself if you can't pull the prebuilt one.
`;
}

function sumRows(tables: Record<string, number>): number {
  return Object.values(tables).reduce((a, b) => a + b, 0);
}

/** Human-friendly byte size, e.g. `1.4 GB`. */
export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB', 'TB'];
  let value = bytes / 1024;
  let i = 0;
  while (value >= 1024 && i < units.length - 1) {
    value /= 1024;
    i += 1;
  }
  return `${value.toFixed(1)} ${units[i]}`;
}
